### ISSUE TITLE
Tracking issues

### ISSUE THREAD

**Issue by gavinleroy** [cognitive-engineering-lab/argus#3]
## IDE

- [ ] we rely on the `TypeckResults` from rustc for getting reported errors, but this isn't robust for range mapping nor for accurate obligation linking. We may need to submit a patch to rustc making certain diagnostic functions public to avoid lots of duplication.
- [ ] rich tree interaction. inverting and re-rooting the tree at specified nodes.
- [ ] generate SVG for bottom up view (highlighting error path)
- [ ] proper `ThemeColor`s in the extension. CSS variables don't seem to be the same here as in the webview...

## Argus

- [ ] profile tree generation. this is *not so fast* (an understatement) but can consume a worrying amount of memory. (See `chumsky` test.)
- [ ] hide resolved obligations. meaning a specific obligation `_: Trait` is evaluated to ambiguous, but then the type of `_` becomes known and the query succeeds (or fails). We really only want to show users the end result of this, not the inference queries in the middle. In past conversations we've formulated this as "obligations that imply the result of another".

## Infrastructure

- [ ] release workflow for publishing
- [ ] publish documentation and tutorial book to <CEL>.github.io

## Documentation

- [ ] we need an Argus icon UwU
- [ ] better demo and information in README.
- [ ] the code is (sadly) mostly undocumented.
- [ ] the tutorial book is barely started, and the start that's there is weak. Missing core examples for Bevy, async, and overflow.

**Comment by gavinleroy** [comment]
Remaining todos are out of date, closing in favor of individual issues.
