### ISSUE TITLE
The rustc devs version checklist

### ISSUE THREAD

**Issue by gavinleroy** [cognitive-engineering-lab/argus#40]
TODO in Argus
- [ ] `NormalizesTo` writes the result to the `Term`, we need to let this run to completion before serializing. 
- [ ] investigate if we can look use `visit_goal` instead of `visit_with`. (i didn't think we could be that may have changed)
- [ ] clone the `orig_values` struct and show everything that was constrained by the goal. (this would be hidden behind a checkbox in the ide)
- [ ] just get rid of `root` candidates nobody thinks they're useful

To upstream to rustc
- [ ] `CandidateSource::ForcedAmbiguity` should exist, it's currently a `Misc` source
- [ ] make `visit_with` public if we can't use `visit_goal`
- [ ] assign predicates a unique id when they first come into the solver. we can then eliminate previous iterations of the same predicate—we only care about the last iteration. the trick is this cannot cause a regression in the compiler.
